(()=>{'use strict';
const DB='gvault_trace_vfs_v1',VER=1,MAX_EVENTS=600,SEAL_BATCH=180,SEAL_EVERY_MS=45000,FLUSH_EVERY_MS=90000;
const PUBLIC_REPO='mourchoua-commits/Gvault-Pages',SPOOL_BRANCH='datapassiv',EPOCH='20260827',KID='8b67e32735e3ed0a';
const KEY_URL='https://raw.githubusercontent.com/'+PUBLIC_REPO+'/'+SPOOL_BRANCH+'/keys/datapassiv-20260827-public.json';
const sessionId=(crypto.randomUUID?.()||('s_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2)));
let dbP=null,seq=Date.now()*1000,busySeal=false,busyFlush=false,lastKey=null;
const enc=new TextEncoder();
function req(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function txDone(t){return new Promise((res,rej)=>{t.oncomplete=()=>res();t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error||new Error('tx aborted'))})}
function db(){if(dbP)return dbP;dbP=new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('events'))d.createObjectStore('events',{keyPath:'seq'});if(!d.objectStoreNames.contains('outbox'))d.createObjectStore('outbox',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbP}
function safe(v){if(v==null)return v;if(typeof v==='number'||typeof v==='boolean')return v;return String(v).replace(/github_pat_[A-Za-z0-9_]+/g,'[REDACTED]').replace(/gh[pousr]_[A-Za-z0-9]+/g,'[REDACTED]').replace(/Bearer\s+\S+/gi,'Bearer [REDACTED]').slice(0,1200)}
function detailObj(o={}){const out={};for(const [k,v] of Object.entries(o)){if(/password|token|authorization|value/i.test(k))continue;out[k]=safe(v)}return out}
function targetInfo(el){if(!el||el.nodeType!==1)return {};const sensitive=el.matches?.('input,textarea,select,[contenteditable="true"]');return {tag:el.tagName?.toLowerCase()||'',id:safe(el.id||''),action:safe(el.dataset?.gvbsTool||el.dataset?.action||el.getAttribute?.('data-action')||''),role:safe(el.getAttribute?.('role')||''),sensitive:Boolean(sensitive)}}
async function put(store,val){const d=await db(),t=d.transaction(store,'readwrite');t.objectStore(store).put(val);await txDone(t)}
async function countEvents(){const d=await db(),t=d.transaction('events','readonly');return req(t.objectStore('events').count())}
async function firstEvents(n){const d=await db(),t=d.transaction('events','readonly'),s=t.objectStore('events'),out=[];return new Promise((res,rej)=>{const r=s.openCursor();r.onerror=()=>rej(r.error);r.onsuccess=()=>{const c=r.result;if(!c||out.length>=n)return res(out);out.push(c.value);c.continue()}})}
async function deleteSeqs(list){if(!list.length)return;const d=await db(),t=d.transaction('events','readwrite'),s=t.objectStore('events');for(const x of list)s.delete(x.seq);await txDone(t)}
async function listOutbox(){const d=await db(),t=d.transaction('outbox','readonly');return req(t.objectStore('outbox').getAll())}
async function record(type,detail={}){const ev={schema:'GVAULT_TRACE_EVENT_V1',seq:++seq,at:new Date().toISOString(),sessionId,type,detail:detailObj(detail)};try{await put('events',ev);const n=await countEvents();if(n>MAX_EVENTS)await sealOldest(Math.max(SEAL_BATCH,n-MAX_EVENTS))}catch(e){console.warn('[TRACE VFS]',e)}return ev}
function b64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
async function sha256(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function loadKey(){if(lastKey)return lastKey;const r=await fetch(KEY_URL,{cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error('datapassiv key HTTP '+r.status);const j=await r.json();if(j.kid!==KID)throw new Error('datapassiv kid mismatch');const key=await crypto.subtle.importKey('jwk',j.jwk,{name:'RSA-OAEP',hash:'SHA-256'},false,['encrypt']);return lastKey={meta:j,key}}
async function sealEvents(events){if(!events.length)return null;const {key}=await loadKey(),aes=await crypto.subtle.generateKey({name:'AES-GCM',length:256},true,['encrypt']),raw=new Uint8Array(await crypto.subtle.exportKey('raw',aes)),iv=crypto.getRandomValues(new Uint8Array(12));const plain=enc.encode(JSON.stringify({schema:'GVAULT_TRACE_BATCH_V1',createdAt:new Date().toISOString(),sessionId,eventCount:events.length,seqFirst:events[0].seq,seqLast:events[events.length-1].seq,events}));const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},aes,plain)),wrapped=new Uint8Array(await crypto.subtle.encrypt({name:'RSA-OAEP'},key,raw)),id=(crypto.randomUUID?.()||Math.random().toString(36).slice(2));return {schema:'GVAULT_DATAPASSIV_CAPSULE_V1',id,createdAt:new Date().toISOString(),epoch:EPOCH,kid:KID,source:{repository:PUBLIC_REPO,surface:location.pathname,sessionId},eventCount:events.length,seqFirst:events[0].seq,seqLast:events[events.length-1].seq,alg:{cipher:'AES-256-GCM',wrap:'RSA-OAEP-256'},iv:b64(iv),wrappedKey:b64(wrapped),ciphertext:b64(cipher),ciphertextSha256:await sha256(cipher),state:'LOCAL_OUTBOX',attempts:0}}
async function sealOldest(n=SEAL_BATCH){if(busySeal)return null;busySeal=true;try{const events=await firstEvents(n);if(!events.length)return null;const capsule=await sealEvents(events);await put('outbox',capsule);await deleteSeqs(events);window.dispatchEvent(new CustomEvent('gvault:trace-capsule',{detail:{id:capsule.id,eventCount:capsule.eventCount,state:capsule.state}}));return capsule}finally{busySeal=false}}
async function sealPending(){const n=await countEvents();if(n>=40)return sealOldest(Math.min(SEAL_BATCH,n));return null}
async function flush(){if(busyFlush)return;const url=String(window.GVAULT_DATAPASSIV_INGEST_URL||'').trim();if(!url)return;busyFlush=true;try{for(const c of (await listOutbox()).filter(x=>x.state!=='SENT')){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c),keepalive:true,credentials:'omit'});if(!r.ok)throw new Error('ingest HTTP '+r.status);c.state='SENT';c.sentAt=new Date().toISOString();c.attempts=(c.attempts||0)+1;await put('outbox',c);window.dispatchEvent(new CustomEvent('gvault:trace-sent',{detail:{id:c.id}}))}catch(e){c.attempts=(c.attempts||0)+1;c.lastError=safe(e.message||e);await put('outbox',c);window.dispatchEvent(new CustomEvent('gvault:trace-send-error',{detail:{id:c.id,error:c.lastError}}))}}}finally{busyFlush=false}}
function hookWindow(w,d,label='runtime'){if(!w||!d||d.__gvaultTraceHooked)return;d.__gvaultTraceHooked=true;d.addEventListener('pointerup',e=>{const t=targetInfo(e.target);if(t.sensitive)return;record('pointer.click',{scope:label,pointerType:e.pointerType||'unknown',button:e.button,x1000:Math.round((e.clientX/Math.max(1,w.innerWidth))*1000),y1000:Math.round((e.clientY/Math.max(1,w.innerHeight))*1000),...t})},true);d.addEventListener('click',e=>{const b=e.target?.closest?.('[data-gvbs-tool]');if(b)record('blop.tool.click',{tool:b.dataset.gvbsTool||'',disabled:!!b.disabled,ready:!!d.querySelector('#gvaultRuntime')?.classList.contains('ready')})},true);w.addEventListener('error',e=>record('runtime.error',{scope:label,message:e.message||'',source:(e.filename||'').split('/').slice(-2).join('/'),line:e.lineno||0,col:e.colno||0}));w.addEventListener('unhandledrejection',e=>record('runtime.rejection',{scope:label,reason:e.reason?.message||String(e.reason||'unknown')}));w.addEventListener('online',()=>record('network.online',{scope:label}));w.addEventListener('offline',()=>record('network.offline',{scope:label}));try{if('PerformanceObserver'in w){const po=new w.PerformanceObserver(list=>{for(const x of list.getEntries())if(x.duration>=50)record('performance.longtask',{scope:label,duration:Math.round(x.duration),start:Math.round(x.startTime)})});po.observe({type:'longtask',buffered:true})}}catch{}}
async function stats(){return {schema:'GVAULT_TRACE_VFS_STATUS_V1',sessionId,events:await countEvents(),outbox:(await listOutbox()).map(x=>({id:x.id,state:x.state,eventCount:x.eventCount,attempts:x.attempts||0,lastError:x.lastError||''})),transport:{endpoint:Boolean(window.GVAULT_DATAPASSIV_INGEST_URL)},epoch:EPOCH,kid:KID}}
window.GVAULT_TRACE_VFS=Object.freeze({schema:'GVAULT_TRACE_VFS_V1',record,sealPending,flush,stats,hookWindow,constants:{MAX_EVENTS,SEAL_BATCH,EPOCH,KID,SPOOL_BRANCH}});
record('trace.start',{surface:location.pathname,referrerPresent:Boolean(document.referrer)});hookWindow(window,document,'harness');setInterval(()=>void sealPending(),SEAL_EVERY_MS);setInterval(()=>void flush(),FLUSH_EVERY_MS);window.addEventListener('pagehide',()=>void record('trace.pagehide'),{once:true});
})();
