import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'gvault-public-scout-test-'));
const rawPath=path.join(tmp,'raw.json'),translatedPath=path.join(tmp,'translated.json'),outDir=path.join(tmp,'data'),ackDir=path.join(tmp,'ack'),buildPath=path.join(tmp,'build.json'),ackResultPath=path.join(tmp,'ack-result.json');
const body=JSON.stringify([{sha:'a'.repeat(40),commit:{committer:{date:'2026-08-30T00:00:00Z'},message:'public update ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'},html_url:'https://github.com/example/repo/commit/'+ 'a'.repeat(40)}]);
const bodySha256=crypto.createHash('sha256').update(Buffer.from(body,'utf8')).digest('hex');
const selectedUrl='https://raw.githubusercontent.com/example/repo/main/manifest.json';
fs.writeFileSync(rawPath,JSON.stringify({schema:'GVAULT_PUBLIC_SCOUT_BLACK_RAW_V1',version:1,request:{requestId:'TEST-1',topic:'test-topic',requestedUrl:'https://api.github.com/repos/example/repo/commits',selectedUrl,sourceIndex:1,method:'GET'},attempts:[{index:0,url:'https://api.github.com/repos/example/repo/commits',status:'FETCH_FAILED',error:'PUBLIC_SCOUT_HTTP_403'},{index:1,url:selectedUrl,status:'PASS',httpStatus:200,utf8Bytes:Buffer.byteLength(body,'utf8'),bodySha256}],fetch:{status:200,contentType:'application/json',utf8Bytes:Buffer.byteLength(body,'utf8'),bodySha256,fetchedAt:'2026-08-30T00:00:00Z',safeHeaders:{}},body,trust:'UNTRUSTED_PUBLIC_INPUT',translationPerformed:false,credentialsObservedByScanner:false},null,2));
execFileSync(process.execPath,[path.join(here,'public-scout-white.mjs'),'--input',rawPath,'--out',translatedPath],{cwd:root,stdio:'pipe'});
const translated=JSON.parse(fs.readFileSync(translatedPath,'utf8'));
assert.equal(translated.integrity,'PASS');
assert.equal(translated.rawBodyPublished,false);
assert.equal(translated.networkUsed,false);
assert.equal(translated.sourceUrl,selectedUrl);
assert.equal(translated.scanSourceIndex,1);
assert.equal(translated.scanAttemptCount,2);
assert.match(translated.facts[0].summary,/\[REDACTED\]/);
assert.doesNotMatch(JSON.stringify(translated),/ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ/);

const buildState=()=>execFileSync(process.execPath,[path.join(here,'public-scout-build-state.mjs'),'--input',translatedPath,'--out-dir',outDir,'--build-result',buildPath],{cwd:root,stdio:'pipe'});
buildState();
let latest=JSON.parse(fs.readFileSync(path.join(outDir,'latest.json'),'utf8'));
let build=JSON.parse(fs.readFileSync(buildPath,'utf8'));
assert.equal(build.changed,true);
assert.equal(latest.status,'PASS');
assert.equal(latest.integrity.rawBodyPublished,false);
assert.equal(latest.integrity.privateCredentialRequired,false);
assert.match(latest.rangers.black.message,/Power Ranger Noir/);
assert.match(latest.rangers.white.message,/Power Ranger Blanc/);
assert.match(latest.rangers.publisher.signal,/^PR1:WH:P:OK:[a-f0-9]{12}$/);
assert.match(build.commitSubject,/Megazord|boss/i);
assert.doesNotMatch(JSON.stringify(latest),/ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ/);
assert.doesNotMatch(JSON.stringify(latest),/"body"\s*:/);
const firstStateSha=latest.publicStateSha256;
buildState();build=JSON.parse(fs.readFileSync(buildPath,'utf8'));latest=JSON.parse(fs.readFileSync(path.join(outDir,'latest.json'),'utf8'));
assert.equal(build.changed,false);
assert.equal(latest.publicStateSha256,firstStateSha);

const dataCommit='c'.repeat(40);
const buildAck=()=>execFileSync(process.execPath,[path.join(here,'public-scout-build-ack.mjs'),'--state',path.join(outDir,'latest.json'),'--data-commit',dataCommit,'--out-dir',ackDir,'--result',ackResultPath],{cwd:root,stdio:'pipe'});
buildAck();
let ack=JSON.parse(fs.readFileSync(path.join(ackDir,'latest.json'),'utf8'));
let ackResult=JSON.parse(fs.readFileSync(ackResultPath,'utf8'));
assert.equal(ackResult.changed,true);
assert.equal(ack.dataCommitSha,dataCommit);
assert.equal(ack.publicStateSha256,firstStateSha);
assert.equal(ack.rawBodyPublished,false);
assert.equal(ack.privateDataPublished,false);
assert.match(ack.ranger.signal,/^PR1:RD:A:OK:[a-f0-9]{12}$/);
assert.match(ack.ranger.message,/Power Ranger Rouge/);
const firstAckDigest=ack.ackDigest;
buildAck();ackResult=JSON.parse(fs.readFileSync(ackResultPath,'utf8'));ack=JSON.parse(fs.readFileSync(path.join(ackDir,'latest.json'),'utf8'));
assert.equal(ackResult.changed,false);
assert.equal(ack.ackDigest,firstAckDigest);
assert.doesNotMatch(JSON.stringify(ack),/ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ|"body"\s*:/);

const blackSource=fs.readFileSync(path.join(here,'public-scout-black.mjs'),'utf8');
assert.doesNotMatch(blackSource,/GITHUB_TOKEN|secrets\.|Authorization\s*:/i);
const whiteSource=fs.readFileSync(path.join(here,'public-scout-white.mjs'),'utf8');
assert.doesNotMatch(whiteSource,/\bfetch\s*\(|node:https|node:http|https:\/\//);
console.log(JSON.stringify({schema:'GVAULT_PUBLIC_SCOUT_PIPELINE_TEST_V2',status:'PASS',assertions:32,translationDigest:latest.translationDigest,publicStateSha256:firstStateSha,ackDigest:firstAckDigest,dataCommit},null,2));
