import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';

const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'gvault-public-scout-test-'));
const rawPath=path.join(tmp,'raw.json'),translatedPath=path.join(tmp,'translated.json'),outDir=path.join(tmp,'data'),buildPath=path.join(tmp,'build.json');
const body=JSON.stringify([{sha:'a'.repeat(40),commit:{committer:{date:'2026-08-30T00:00:00Z'},message:'public update ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'},html_url:'https://github.com/example/repo/commit/'+ 'a'.repeat(40)}]);
const bodySha256=crypto.createHash('sha256').update(Buffer.from(body,'utf8')).digest('hex');
fs.writeFileSync(rawPath,JSON.stringify({schema:'GVAULT_PUBLIC_SCOUT_BLACK_RAW_V1',version:1,request:{requestId:'TEST-1',topic:'test-topic',url:'https://api.github.com/repos/example/repo/commits',method:'GET'},fetch:{status:200,contentType:'application/json',utf8Bytes:Buffer.byteLength(body,'utf8'),bodySha256,fetchedAt:'2026-08-30T00:00:00Z',safeHeaders:{}},body,trust:'UNTRUSTED_PUBLIC_INPUT',translationPerformed:false,credentialsObservedByScanner:false},null,2));
execFileSync(process.execPath,[path.join(here,'public-scout-white.mjs'),'--input',rawPath,'--out',translatedPath],{cwd:root,stdio:'pipe'});
const translated=JSON.parse(fs.readFileSync(translatedPath,'utf8'));
assert.equal(translated.integrity,'PASS');
assert.equal(translated.rawBodyPublished,false);
assert.equal(translated.networkUsed,false);
assert.match(translated.facts[0].summary,/\[REDACTED\]/);
assert.doesNotMatch(JSON.stringify(translated),/ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ/);
execFileSync(process.execPath,[path.join(here,'public-scout-build-state.mjs'),'--input',translatedPath,'--out-dir',outDir,'--build-result',buildPath],{cwd:root,stdio:'pipe'});
const latest=JSON.parse(fs.readFileSync(path.join(outDir,'latest.json'),'utf8'));
const build=JSON.parse(fs.readFileSync(buildPath,'utf8'));
assert.equal(latest.status,'PASS');
assert.equal(latest.integrity.rawBodyPublished,false);
assert.equal(latest.integrity.privateCredentialRequired,false);
assert.match(latest.rangers.black.message,/Power Ranger Noir/);
assert.match(latest.rangers.white.message,/Power Ranger Blanc/);
assert.match(latest.rangers.publisher.signal,/^PR1:WH:P:OK:[a-f0-9]{12}$/);
assert.match(build.commitSubject,/Megazord|boss/i);
assert.doesNotMatch(JSON.stringify(latest),/ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZ/);
assert.doesNotMatch(JSON.stringify(latest),/"body"\s*:/);
const blackSource=fs.readFileSync(path.join(here,'public-scout-black.mjs'),'utf8');
assert.doesNotMatch(blackSource,/GITHUB_TOKEN|secrets\.|Authorization\s*:/i);
const whiteSource=fs.readFileSync(path.join(here,'public-scout-white.mjs'),'utf8');
assert.doesNotMatch(whiteSource,/\bfetch\s*\(|node:https|node:http|https:\/\//);
console.log(JSON.stringify({schema:'GVAULT_PUBLIC_SCOUT_PIPELINE_TEST_V1',status:'PASS',assertions:14,translationDigest:latest.translationDigest,publicStateSha256:latest.publicStateSha256},null,2));
