import {normalizeEvent,sortEvents,dedupeEvents,buildTrack,buildSwarmContamination,applyEventsToTracks,extractAnchors,safeString,activeContaminationForEvent,rootContaminationForEvent,setSwarmContaminationActive} from './core-v2.mjs';

const LOCAL_TRACK_KEY='gvault.controlTower.tracks.v3';
const LOCAL_OUTBOX_KEY='gvault.controlTower.trackOutbox.v1';
const LEGACY_DB='gvault-control-tower-credential-v1';
const POLL_MS=30000;
let password='',events=[],tracks=[],selected=null,mode='LIVE',search='',pollTimer=null,lastRefresh=null,lastPayload='',feedMeta=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const log=(line,cls='')=>{const box=$('#terminalLog');if(!box)return;const p=document.createElement('div');p.className=cls;p.textContent=`${new Date().toLocaleTimeString()}  ${line}`;box.appendChild(p);box.scrollTop=box.scrollHeight};
function setStatus(text,kind=''){const n=$('#connectionState');n.textContent=text;n.dataset.kind=kind}
const bufToHex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256Bytes(b){return bufToHex(await crypto.subtle.digest('SHA-256',b))}
function b64bytes(s){const bin=atob(String(s||''));return Uint8Array.from(bin,c=>c.charCodeAt(0))}

async function deleteLegacyCredentialDb(){if(!('indexedDB' in window))return;await new Promise(resolve=>{try{const r=indexedDB.deleteDatabase(LEGACY_DB);r.onsuccess=r.onerror=r.onblocked=()=>resolve()}catch{resolve()}})}
function loadLocalTracks(){try{const x=JSON.parse(localStorage.getItem(LOCAL_TRACK_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function saveLocalTracks(){localStorage.setItem(LOCAL_TRACK_KEY,JSON.stringify(tracks))}
function appendOutbox(action,track){let rows=[];try{rows=JSON.parse(localStorage.getItem(LOCAL_OUTBOX_KEY)||'[]');if(!Array.isArray(rows))rows=[]}catch{rows=[]}const op={schema:'GVAULT_CONTROL_TOWER_TRACK_OUTBOX_V1',opId:`CTOP-${Date.now()}-${Math.random().toString(36).slice(2,9)}`,at:new Date().toISOString(),action,track:structuredClone(track),state:'LOCAL_PENDING_SERVER_BRIDGE'};rows.push(op);localStorage.setItem(LOCAL_OUTBOX_KEY,JSON.stringify(rows.slice(-500)));return op}
function outboxCount(){try{const x=JSON.parse(localStorage.getItem(LOCAL_OUTBOX_KEY)||'[]');return Array.isArray(x)?x.length:0}catch{return 0}}

async function fetchManifest(){const r=await fetch('./data/manifest.json?ts='+Date.now(),{cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error('feed manifest HTTP '+r.status);const m=await r.json();if(m.schema!=='GVAULT_CONTROL_TOWER_ENCRYPTED_FEED_V1')throw new Error('feed manifest schema');return m}
async function decryptFeed(secret,force=false){const m=await fetchManifest();if(!force&&lastPayload&&m.payload?.path===lastPayload)return null;if(!m.payload?.path||!m.payload?.sha256||!m.crypto?.saltB64||!m.crypto?.ivB64)throw new Error('feed manifest incomplet');const r=await fetch('./data/'+m.payload.path+'?ts='+Date.now(),{cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error('feed payload HTTP '+r.status);const cipher=await r.arrayBuffer();if(cipher.byteLength!==Number(m.payload.size))throw new Error('feed payload size mismatch');if(await sha256Bytes(cipher)!==m.payload.sha256)throw new Error('feed payload SHA mismatch');const raw=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64bytes(m.crypto.saltB64),iterations:Number(m.crypto.iterations),hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['decrypt']);let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64bytes(m.crypto.ivB64)},key,cipher)}catch{throw new Error('mot de passe SAS incorrect ou feed invalide')}if(plain.byteLength!==Number(m.source.size))throw new Error('feed plain size mismatch');if(await sha256Bytes(plain)!==m.source.sha256)throw new Error('feed plain SHA mismatch');const feed=JSON.parse(new TextDecoder().decode(plain));if(feed.schema!=='GVAULT_CONTROL_TOWER_FEED_V1')throw new Error('feed schema');lastPayload=m.payload.path;feedMeta={manifest:m,feed};return feed}
function eventsFromFeed(feed){const out=[];for(const src of feed.sources||[])(src.records||[]).forEach((raw,i)=>out.push(normalizeEvent(raw,src.engine||'unknown',src.path||'feed',i)));return sortEvents(dedupeEvents(out))}
function mergeTracks(remote=[]){const local=loadLocalTracks();const map=new Map();for(const t of remote||[])map.set(t.trackId,t);for(const t of local)map.set(t.trackId,t);tracks=[...map.values()];saveLocalTracks()}
async function refresh(force=false){if(!password)return;setStatus('SYNC…','busy');const start=performance.now();try{const feed=await decryptFeed(password,force);if(feed){events=eventsFromFeed(feed);mergeTracks(feed.trackRegistry?.tracks||[]);const changed=applyEventsToTracks(tracks,events);if(changed)saveLocalTracks();lastRefresh=new Date(feed.generatedAt||Date.now())}renderAll();setStatus(`LIVE · ${events.length} événements`,'ok');log(`refresh PASS · ${events.length} événements · ${tracks.length} suivis · outbox=${outboxCount()} · ${Math.round(performance.now()-start)} ms`,'ok')}catch(e){setStatus('DEGRADED','bad');log('refresh FAIL · '+e.message,'bad');throw e}}
function filteredEvents(){let x=events;if(mode==='ALERTES')x=x.filter(e=>['critical','warning'].includes(e.severity));if(mode==='SUIVIS'){const ids=new Set(tracks.flatMap(t=>(t.matches||[]).map(m=>m.eventId)));x=x.filter(e=>ids.has(e.id))}if(search.trim()){const q=search.toLowerCase();x=x.filter(e=>safeString(e).toLowerCase().includes(q))}return x}
function engineCounts(){const m={};for(const e of events)m[e.engine]=(m[e.engine]||0)+1;return m}
function formatTime(v){const d=new Date(v);return Number.isNaN(+d)?String(v||'').slice(0,19):d.toLocaleString()}
function severityGlyph(s){return s==='critical'?'◆':s==='warning'?'▲':s==='ok'?'●':'·'}
function renderEngines(){const m=engineCounts();$('#engineList').innerHTML=Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<button data-engine="${esc(k)}"><span>${esc(k)}</span><b>${v}</b></button>`).join('')||'<div class="empty">aucun moteur chargé</div>';document.querySelectorAll('[data-engine]').forEach(b=>b.onclick=()=>{$('#search').value=b.dataset.engine;search=b.dataset.engine;renderEvents()})}
function renderEvents(){const x=filteredEvents();$('#eventCount').textContent=x.length;const contaminated=new Set(tracks.filter(t=>t.mode==='SWARM_CONTAMINATION'&&t.state==='ACTIVE'&&t.propagation?.active!==false).flatMap(t=>(t.matches||[]).map(m=>m.eventId)));const roots=new Map(tracks.filter(t=>t.mode==='SWARM_CONTAMINATION').map(t=>[t.originEventId,t]));$('#eventList').innerHTML=x.slice(0,500).map(e=>{const marked=contaminated.has(e.id),root=roots.get(e.id);return `<article class="event ${e.severity} ${selected?.id===e.id?'selected':''} ${marked?'contaminated':''}"><button class="eventMain" data-open="${esc(e.id)}"><div class="eventTop"><span class="sev">${severityGlyph(e.severity)}</span><b>${esc(e.engine)}</b>${marked?'<span class="workMark">WORK</span>':''}<time>${esc(formatTime(e.at))}</time></div><div class="summary">${esc(e.summary)}</div><div class="meta">${esc(e.type)}${e.status?' · '+esc(e.status):''}${e.project?' · '+esc(e.project):''}</div></button><button class="tagBtn" title="Tag / suivre" data-tag="${esc(e.id)}">⌖</button><button class="swarmBtn ${marked?'active':''} ${root&&root.state!=='ACTIVE'?'paused':''}" title="SWARM contamination" data-swarm="${esc(e.id)}">☣</button></article>`}).join('')||'<div class="empty">aucun événement pour ce filtre</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>selectEvent(b.dataset.open));document.querySelectorAll('[data-tag]').forEach(b=>b.onclick=e=>{e.stopPropagation();openTrackDialog(b.dataset.tag)});document.querySelectorAll('[data-swarm]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleSwarmFromEvent(b.dataset.swarm)})}
function selectEvent(id){selected=events.find(e=>e.id===id)||null;renderEvents();renderDetail()}
function renderDetail(){const e=selected;if(!e){$('#detail').innerHTML='<div class="empty big">Sélectionne un événement pour descendre jusqu’à sa preuve.</div>';return}const anchors=extractAnchors(e),sw=activeContaminationForEvent(tracks,e.id),root=rootContaminationForEvent(tracks,e.id);$('#detail').innerHTML=`<div class="detailHead"><div><span class="badge ${e.severity}">${esc(e.severity)}</span><h2>${esc(e.engine)}</h2></div><div class="detailActions"><button id="detailTrack">TAG / SUIVRE</button><button id="detailSwarm" class="${sw?'active':''}">${sw?'☣ CONTAMINATION ACTIVE':root?'☣ RÉACTIVER':'☣ SWARM'}</button></div></div><h3>${esc(e.summary)}</h3>${sw?`<div class="swarmBanner">WORK_SPECIAL · ${esc(sw.workSpecial?.workId||sw.trackId)} · ramification suivie</div>`:''}<dl><dt>ID</dt><dd>${esc(e.id)}</dd><dt>TYPE</dt><dd>${esc(e.type)}</dd><dt>STATUT</dt><dd>${esc(e.status||'—')}</dd><dt>DATE</dt><dd>${esc(formatTime(e.at))}</dd><dt>SHA</dt><dd>${esc(e.sha||'—')}</dd></dl><section><b>ANCRES</b><div class="chips">${anchors.map(a=>`<span>${esc(a.key)}=${esc(a.value)}</span>`).join('')||'<i>aucune ancre stable</i>'}</div></section><section><b>PREUVES</b>${(e.proofRefs||[]).map(p=>`<div class="proof">${esc(p)}</div>`).join('')||'<i>aucune référence explicite</i>'}</section><section><b>ÉVÉNEMENT BRUT</b><pre>${esc(JSON.stringify(e.raw,null,2))}</pre></section>`;$('#detailTrack').onclick=()=>openTrackDialog(e.id);$('#detailSwarm').onclick=()=>toggleSwarmFromEvent(e.id)}
function renderTracks(){const box=$('#trackList');box.innerHTML=tracks.map(t=>{const swarm=t.mode==='SWARM_CONTAMINATION',pending=t.propagation?.pendingCandidates?.length||0;return `<article class="track ${swarm?'swarmTrack':''} ${t.state==='ACTIVE'?'active':''}"><div class="trackTop"><b>${esc(t.trackId)}</b><span>${esc(t.syncState||'LOCAL_PENDING')}</span></div><h3>${swarm?'☣ ':''}${esc(t.label)}</h3><div class="trackMeta">${esc(t.engine)} · ${(t.matches||[]).length} événement(s) · ${esc(t.state)}${swarm?` · WORK ${esc(t.workSpecial?.workId||'')}`:''}${pending?` · ${pending} ambiguë(s)`:''}</div><div class="chips">${(t.anchors||[]).map(a=>`<span>${esc(a.key)}=${esc(a.value)}</span>`).join('')}</div><div class="trackActions"><button data-showtrack="${esc(t.trackId)}">TIMELINE</button><button data-paused="${esc(t.trackId)}">${swarm?(t.state==='ACTIVE'?'STOP CONTAMINATION':'RÉACTIVER'):(t.state==='ACTIVE'?'PAUSE':'REPRENDRE')}</button></div></article>`}).join('')||'<div class="empty">aucune information taguée</div>';document.querySelectorAll('[data-showtrack]').forEach(b=>b.onclick=()=>showTrack(b.dataset.showtrack));document.querySelectorAll('[data-paused]').forEach(b=>b.onclick=()=>toggleTrack(b.dataset.paused))}
function showTrack(id){const t=tracks.find(x=>x.trackId===id);if(!t)return;$('#trackTimelineTitle').textContent=`${t.trackId} · ${t.label}`;const pending=t.propagation?.pendingCandidates||[];$('#trackTimeline').innerHTML=(t.mode==='SWARM_CONTAMINATION'?`<div class="swarmBanner">WORK_SPECIAL · ${esc(t.workSpecial?.workId||'—')} · propagation ${t.state==='ACTIVE'?'ACTIVE':'STOPPÉE'} · ${pending.length} ambiguë(s)</div>`:'')+(t.matches||[]).slice().sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0)).map(m=>`<div class="timelineItem ${m.kind==='SWARM_DESCENDANT'?'swarmItem':''}"><time>${esc(formatTime(m.at))}</time><b>${esc(m.engine)} · ${esc(m.type)}</b><p>${esc(m.summary)}</p><small>${esc(m.sha||m.eventId)}</small></div>`).join('');if(!$('#trackTimeline').innerHTML)$('#trackTimeline').innerHTML='<div class="empty">aucun match</div>';$('#trackModal').showModal()}
function persistMutation(action,t){t.syncState='LOCAL_PENDING_SERVER_BRIDGE';saveLocalTracks();appendOutbox(action,t);renderAll();log(`${action} · ${t.trackId} · sauvegardé localement · bridge serveur en attente`,'warn')}
function toggleTrack(id){const t=tracks.find(x=>x.trackId===id);if(!t)return;if(t.mode==='SWARM_CONTAMINATION')setSwarmContaminationActive(t,t.state!=='ACTIVE');else{t.state=t.state==='ACTIVE'?'PAUSED':'ACTIVE';t.updatedAt=new Date().toISOString()}if(t.state==='ACTIVE')applyEventsToTracks([t],events);persistMutation('TRACK_TOGGLE',t)}
function toggleSwarmFromEvent(id){const e=events.find(x=>x.id===id);if(!e)return;let t=rootContaminationForEvent(tracks,id)||activeContaminationForEvent(tracks,id);if(t){setSwarmContaminationActive(t,t.state!=='ACTIVE')}else{t=buildSwarmContamination(e,e.summary.slice(0,80),'Marquage ramifié depuis Control Tower');tracks.unshift(t);applyEventsToTracks([t],events)}persistMutation('SWARM_TOGGLE',t)}
function openTrackDialog(id){const e=events.find(x=>x.id===id);if(!e)return;selected=e;$('#trackLabel').value=e.summary.slice(0,80);$('#trackNote').value='';$('#trackOrigin').textContent=`${e.engine} · ${e.id}`;const anchors=extractAnchors(e).filter(a=>a.key!=='type');$('#trackAnchors').innerHTML=anchors.map((a,i)=>`<label><input type="checkbox" checked data-anchor-idx="${i}"> ${esc(a.key)} = ${esc(a.value)}</label>`).join('')||'<i>Aucune ancre stable.</i>';$('#trackDialog').dataset.eventId=id;$('#trackDialog').showModal()}
function confirmTrack(){const id=$('#trackDialog').dataset.eventId,e=events.find(x=>x.id===id);if(!e)return;const t=buildTrack(e,$('#trackLabel').value,$('#trackNote').value);const all=extractAnchors(e).filter(a=>a.key!=='type');t.anchors=[...document.querySelectorAll('[data-anchor-idx]:checked')].map(n=>all[Number(n.dataset.anchorIdx)]).filter(Boolean);tracks.unshift(t);$('#trackDialog').close();persistMutation('TRACK_CREATE',t)}
function renderKpis(){const alerts=events.filter(e=>['critical','warning'].includes(e.severity)).length;$('#kEvents').textContent=events.length;$('#kAlerts').textContent=alerts;$('#kEngines').textContent=Object.keys(engineCounts()).length;$('#kTracks').textContent=tracks.filter(t=>t.state==='ACTIVE').length;$('#lastRefresh').textContent=lastRefresh?lastRefresh.toLocaleTimeString():'—'}
function renderAll(){renderKpis();renderEngines();renderEvents();renderDetail();renderTracks()}
function setMode(m){mode=m;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));renderEvents()}
async function connect(){password=$('#token').value;$('#token').value='';if(!password)return;setStatus('DÉCHIFFREMENT…','busy');try{await refresh(true);log('SAS Control Tower ouvert avec le même mot de passe GVAULT · aucun token GitHub navigateur','ok');if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(()=>refresh(false).catch(()=>{}),POLL_MS)}catch(e){password='';lastPayload='';setStatus('AUTH FAIL','bad');log('SAS FAIL · '+e.message,'bad')}}
function lock(){password='';lastPayload='';feedMeta=null;if(pollTimer)clearInterval(pollTimer);pollTimer=null;events=[];selected=null;setStatus('VERROUILLÉ','');renderAll();log('SAS fermé · secret effacé de la mémoire de la page','warn')}
function runCommand(line){const [cmd,...args]=line.trim().split(/\s+/);if(!cmd)return;const q=args.join(' ');log('> '+line,'cmd');switch(cmd.toLowerCase()){case'help':log('help · live · alerts · tracks · engines · search <texte> · track <TRACK-ID> · swarm <event-id> · refresh · status · outbox · clear');break;case'live':setMode('LIVE');break;case'alerts':setMode('ALERTES');break;case'tracks':setMode('SUIVIS');break;case'engines':log(Object.entries(engineCounts()).map(([k,v])=>`${k}:${v}`).join(' · '));break;case'search':search=q;$('#search').value=q;renderEvents();break;case'track':if(q)showTrack(q);break;case'swarm':if(q)toggleSwarmFromEvent(q);else if(selected)toggleSwarmFromEvent(selected.id);break;case'refresh':refresh(true).catch(()=>{});break;case'outbox':log(`track outbox local pending=${outboxCount()}`,'warn');break;case'status':log(`${$('#connectionState').textContent} · events=${events.length} · tracks=${tracks.length} · outbox=${outboxCount()} · source=${feedMeta?.feed?.source?.vigieCommit?.slice(0,12)||'—'}`);break;case'clear':$('#terminalLog').innerHTML='';break;default:log('commande inconnue · help','warn')}}

document.addEventListener('DOMContentLoaded',async()=>{await deleteLegacyCredentialDb();tracks=loadLocalTracks();renderAll();const input=$('#token');input.placeholder='SAS CONTROL TOWER · même mot de passe GVAULT';input.title='Même mot de passe que le SAS GVAULT. Il sert uniquement à déchiffrer le feed Control Tower et reste en mémoire pendant cette page.';$('#connect').textContent='OUVRIR AVEC SAS GVAULT';$('#connect').onclick=connect;$('#lock').onclick=lock;$('#refresh').onclick=()=>refresh(true).catch(()=>{});$('#search').oninput=e=>{search=e.target.value;renderEvents()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#trackCancel').onclick=()=>$('#trackDialog').close();$('#trackConfirm').onclick=confirmTrack;$('#trackTimelineClose').onclick=()=>$('#trackModal').close();$('#terminalForm').onsubmit=e=>{e.preventDefault();const i=$('#terminalInput');runCommand(i.value);i.value=''};window.GVAULT_CONTROL_TOWER=Object.freeze({schema:'GVAULT_CONTROL_TOWER_V3_ENCRYPTED_FEED',refresh:()=>refresh(true),lock,getState:()=>({events:events.length,tracks:tracks.length,outbox:outboxCount(),lastRefresh,feedSource:feedMeta?.feed?.source||null})});window.addEventListener('pagehide',()=>{password='';if(pollTimer)clearInterval(pollTimer)},{once:true});log('CONTROL TOWER V3 prêt · PAT local retiré · ancien coffre IndexedDB supprimé · utilise le même mot de passe que le SAS GVAULT')});
