const DB='gvault-control-tower-vfs-v1',VER=2,SNAP='snapshots',OPS='mirrorOps';
const $=s=>document.querySelector(s);
let db=null,ticker=null,syncing=false,lastSync=null,lastSyncError='';
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(SNAP))d.createObjectStore(SNAP,{keyPath:'id'});if(!d.objectStoreNames.contains(OPS))d.createObjectStore(OPS,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const tx=(store,mode='readonly')=>db.transaction(store,mode).objectStore(store);
const req=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
const all=store=>req(tx(store).getAll()),put=(store,v)=>req(tx(store,'readwrite').put(v)),clear=store=>req(tx(store,'readwrite').clear()),del=(store,k)=>req(tx(store,'readwrite').delete(k));
const session=()=>window.GVAULT_PRIVATE_TOOL_SESSION_V1,active=()=>!!session()?.getState?.().active,ca=()=>window.GVAULT_CONTENT_ADDRESSED_FEED_V2;
const fmt=v=>{try{return new Date(v).toLocaleString()}catch{return String(v||'—')}};
function ui(){if($('#ctVfs'))return;const host=document.querySelector('.kpis')||document.querySelector('main')||document.body,n=document.createElement('section');n.id='ctVfs';n.innerHTML=`<style>#ctVfs{margin:0 10px 10px;border:1px solid var(--line);border-radius:10px;background:var(--panel);overflow:hidden;font:9px ui-monospace,monospace}.ctVfsHead{display:flex;gap:7px;align-items:center;flex-wrap:wrap;padding:8px;border-bottom:1px solid var(--line)}.ctVfsHead b{color:var(--accent);margin-right:auto}.ctVfsHead button{font-size:8px;padding:7px}.ctVfsState{color:var(--muted)}.ctVfsList{padding:8px;display:grid;gap:6px}.ctVfsRow{border:1px solid var(--line);border-radius:8px;padding:7px;background:var(--panel2)}.ctVfsRowTop{display:flex;justify-content:space-between;gap:7px}.ctVfsMeta{color:var(--muted);margin-top:4px;word-break:break-all}.ctVfsActions{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.ctVfsDanger{border-color:var(--bad)!important;color:var(--bad)!important}#ctVfsDialog{max-width:min(92vw,760px);background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:10px}#ctVfsDialog pre{max-height:55vh;overflow:auto;white-space:pre-wrap;word-break:break-word;font-size:8px}</style><div class="ctVfsHead"><b>VFS CHIFFRÉ · SHA CHAIN</b><span id="ctVfsLease" class="ctVfsState">SAS requis pour lire</span><span id="ctVfsChain" class="ctVfsState">accepté: —</span><span id="ctVfsSync" class="ctVfsState">ciphertext: veille</span><span id="ctVfsMirror" class="ctVfsState">miroir privé: 0</span><button id="ctVfsArchive">SYNC CHAIN</button><button id="ctVfsRefresh">RAFRAÎCHIR</button><button id="ctVfsClear" class="ctVfsDanger">VIDER VFS</button></div><div id="ctVfsList" class="ctVfsList"></div><dialog id="ctVfsDialog"><div id="ctVfsDialogBody"></div><form method="dialog"><button>FERMER</button></form></dialog>`;host.insertAdjacentElement('afterend',n);$('#ctVfsArchive').onclick=()=>syncChain({manual:true,source:'button'});$('#ctVfsRefresh').onclick=render;$('#ctVfsClear').onclick=clearAll}
async function addSnapshot(m,cipher,source='sync'){const chain=m.snapshot?.snapshotChainSha256||m.payload.sha256,id='CTVFS-'+chain.slice(0,20),exists=await req(tx(SNAP).get(id));if(exists)return false;const snap={schema:'GVAULT_CONTROL_TOWER_VFS_SNAPSHOT_V2',id,archivedAt:new Date().toISOString(),ingestSource:source,generatedAt:m.generatedAt||null,manifest:m,cipher:new Blob([cipher],{type:'application/octet-stream'}),payloadSha256:m.payload.sha256,snapshotChainSha256:m.snapshot?.snapshotChainSha256||null,previousSnapshotSha256:m.snapshot?.previousSnapshotSha256||null,sourceMarker:m.snapshot?.sourceMarker||m.source?.sourceMarker||null,size:cipher.byteLength,trustState:'CIPHERTEXT_HASH_VERIFIED_SAS_NOT_REQUIRED'};await put(SNAP,snap);await put(OPS,{schema:'GVAULT_CONTROL_TOWER_VFS_MIRROR_OP_V1',id:'MOP-'+id,at:snap.archivedAt,action:'UPSERT_ENCRYPTED_SNAPSHOT',snapshotId:id,payloadSha256:snap.payloadSha256,snapshotChainSha256:snap.snapshotChainSha256,state:'LOCAL_PENDING_PRIVATE_MIRROR'});return true}
async function syncChain(options={}){if(typeof options==='boolean')options={manual:options};const manual=!!options.manual,source=String(options.source||'sync');if(syncing)return {ok:false,busy:true,added:0};const reader=ca();if(!reader){if(manual)alert('Lecteur SHA indisponible.');return {ok:false,error:'SHA_READER_UNAVAILABLE',added:0}}syncing=true;lastSyncError='';try{const manifests=await reader.walk(48);let added=0;for(const m of manifests.slice().reverse()){const chain=m.snapshot?.snapshotChainSha256||m.payload?.sha256,id='CTVFS-'+String(chain).slice(0,20);if(await req(tx(SNAP).get(id)))continue;const cipher=await reader.fetchCipher(m);if(await addSnapshot(m,cipher,source))added++}lastSync=new Date().toISOString();await render();if(manual&&added===0)alert('VFS déjà à jour.');const result={ok:true,added,walked:manifests.length,source,lastSync};window.dispatchEvent(new CustomEvent('gvault:control-tower-vfs-sync',{detail:result}));return result}catch(e){lastSyncError=String(e?.message||e);await render();if(manual)alert('SYNC CHAIN impossible: '+lastSyncError);const result={ok:false,added:0,source,error:lastSyncError};window.dispatchEvent(new CustomEvent('gvault:control-tower-vfs-sync-failed',{detail:result}));return result}finally{syncing=false}}
async function inspect(id){if(!active()){alert('SAS principal requis pour déchiffrer cette archive.');return}const snap=await req(tx(SNAP).get(id));if(!snap)return;try{const feed=await session().decryptEnvelope(snap.manifest,snap.cipher),engines=(feed.sources||[]).map(s=>({engine:s.engine,path:s.path,records:(s.records||[]).length})),records=engines.reduce((n,x)=>n+x.records,0);snap.trustState='SAS_DECRYPTED_AND_PLAINTEXT_VERIFIED';snap.lastVerifiedAt=new Date().toISOString();await put(SNAP,snap);$('#ctVfsDialogBody').innerHTML=`<h3>${id}</h3><p>archivé: ${fmt(snap.archivedAt)}<br>feed: ${fmt(feed.generatedAt)}<br>sources: ${engines.length} · enregistrements: ${records}<br>CHAIN: ${snap.snapshotChainSha256||'legacy'}<br>PREV: ${snap.previousSnapshotSha256||'—'}<br>BLOB: ${snap.payloadSha256}<br>preuve: ${snap.trustState}</p><pre>${JSON.stringify({source:feed.source,engines,trackRegistry:{tracks:feed.trackRegistry?.tracks?.length||0,workSpecialBindings:feed.trackRegistry?.workSpecialBindings?.length||0}},null,2)}</pre>`;$('#ctVfsDialog').showModal();await render()}catch(e){alert('Déchiffrement VFS refusé: '+e.message)}}
async function removeOne(id){if(!confirm('Supprimer cette archive chiffrée du VFS local ?'))return;await del(SNAP,id);await put(OPS,{schema:'GVAULT_CONTROL_TOWER_VFS_MIRROR_OP_V1',id:'MDEL-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),at:new Date().toISOString(),action:'DELETE_SNAPSHOT',snapshotId:id,state:'LOCAL_PENDING_PRIVATE_MIRROR'});await render()}
async function clearAll(){if(!confirm('VIDER TOUT LE VFS CHIFFRÉ de cet appareil ?'))return;await clear(SNAP);await clear(OPS);await put(OPS,{schema:'GVAULT_CONTROL_TOWER_VFS_MIRROR_OP_V1',id:'MDELALL-'+Date.now(),at:new Date().toISOString(),action:'DELETE_ALL_SNAPSHOTS',state:'LOCAL_PENDING_PRIVATE_MIRROR'});await render()}
async function render(){if(!db)return;const snaps=(await all(SNAP)).sort((a,b)=>String(b.generatedAt||b.archivedAt).localeCompare(String(a.generatedAt||a.archivedAt))),ops=await all(OPS),head=ca()?.getKnown?.();$('#ctVfsMirror').textContent='miroir privé: '+ops.filter(x=>x.state==='LOCAL_PENDING_PRIVATE_MIRROR').length+' en attente';$('#ctVfsChain').textContent='accepté: '+(head?.snapshotChainSha256?.slice(0,12)||'—');const sync=$('#ctVfsSync');if(sync)sync.textContent=lastSyncError?'ciphertext: DEGRADED '+lastSyncError:(lastSync?'ciphertext sync: '+fmt(lastSync):'ciphertext: veille');$('#ctVfsList').innerHTML=snaps.length?snaps.map(s=>`<article class="ctVfsRow"><div class="ctVfsRowTop"><b>${s.id}</b><span>${fmt(s.generatedAt||s.archivedAt)}</span></div><div class="ctVfsMeta">${Number(s.size||0).toLocaleString()} o · chain=${s.snapshotChainSha256?.slice(0,16)||'legacy'} · blob=${s.payloadSha256?.slice(0,16)||'—'} · ${s.trustState||'CIPHERTEXT_ONLY'}</div><div class="ctVfsActions"><button data-vfs-open="${s.id}">CONSULTER</button><button data-vfs-del="${s.id}" class="ctVfsDanger">SUPPRIMER</button></div></article>`}).join(''):'<div class="empty">Aucune archive chiffrée sur cet appareil.</div>';document.querySelectorAll('[data-vfs-open]').forEach(b=>b.onclick=()=>inspect(b.dataset.vfsOpen));document.querySelectorAll('[data-vfs-del]').forEach(b=>b.onclick=()=>removeOne(b.dataset.vfsDel));updateLease()}
function updateLease(){const s=session()?.getState?.(),n=$('#ctVfsLease');if(!n)return;if(!s?.active){n.textContent='SAS requis pour lire';return}const sec=Math.max(0,Math.ceil(s.remainingMs/1000));n.textContent=`lecture privée ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
async function init(){db=await openDb();ui();await render();window.GVAULT_CONTROL_TOWER_VFS_V2=Object.freeze({schema:'GVAULT_CONTROL_TOWER_VFS_V2',syncChain,getState:async()=>({snapshots:(await all(SNAP)).length,pendingMirror:(await all(OPS)).filter(x=>x.state==='LOCAL_PENDING_PRIVATE_MIRROR').length,lastSync,lastSyncError,sasActive:active()})});window.addEventListener('gvault:private-tool-session-active',async()=>{await syncChain({source:'sas-active'});await render()});window.addEventListener('gvault:private-tool-session-expired',render);window.addEventListener('gvault:control-tower-new-public-commit',ev=>void syncChain({source:'commit-event',commitSha:ev.detail?.sha}));ticker=setInterval(updateLease,1000);window.addEventListener('pagehide',()=>clearInterval(ticker),{once:true});await syncChain({source:'startup'})}
init().catch(e=>console.error('[Control Tower encrypted VFS V2]',e));
