const DB='gvault-control-tower-vfs-v1',VER=1,SNAP='snapshots',OPS='mirrorOps',MANIFEST='./data/manifest.json';
const $=s=>document.querySelector(s),hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join(''),sha=async b=>hex(await crypto.subtle.digest('SHA-256',b));
let db=null,ticker=null;
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(SNAP))d.createObjectStore(SNAP,{keyPath:'id'});if(!d.objectStoreNames.contains(OPS))d.createObjectStore(OPS,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const tx=(store,mode='readonly')=>db.transaction(store,mode).objectStore(store);
const req=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});
async function all(store){return req(tx(store).getAll())}
async function put(store,v){return req(tx(store,'readwrite').put(v))}
async function clear(store){return req(tx(store,'readwrite').clear())}
async function del(store,k){return req(tx(store,'readwrite').delete(k))}
function session(){return window.GVAULT_PRIVATE_TOOL_SESSION_V1}
function active(){return !!session()?.getState?.().active}
function fmt(v){try{return new Date(v).toLocaleString()}catch{return String(v||'—')}}
function ui(){if($('#ctVfs'))return;const host=document.querySelector('.kpis')||document.querySelector('main')||document.body;const n=document.createElement('section');n.id='ctVfs';n.innerHTML=`<style>#ctVfs{margin:0 10px 10px;border:1px solid var(--line);border-radius:10px;background:var(--panel);overflow:hidden;font:9px ui-monospace,monospace}.ctVfsHead{display:flex;gap:7px;align-items:center;flex-wrap:wrap;padding:8px;border-bottom:1px solid var(--line)}.ctVfsHead b{color:var(--accent);margin-right:auto}.ctVfsHead button{font-size:8px;padding:7px}.ctVfsState{color:var(--muted)}.ctVfsList{padding:8px;display:grid;gap:6px}.ctVfsRow{border:1px solid var(--line);border-radius:8px;padding:7px;background:var(--panel2)}.ctVfsRowTop{display:flex;justify-content:space-between;gap:7px}.ctVfsMeta{color:var(--muted);margin-top:4px;word-break:break-all}.ctVfsActions{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.ctVfsDanger{border-color:var(--bad)!important;color:var(--bad)!important}#ctVfsDialog{max-width:min(92vw,760px);background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:10px}#ctVfsDialog pre{max-height:55vh;overflow:auto;white-space:pre-wrap;word-break:break-word;font-size:8px}</style><div class="ctVfsHead"><b>VFS CHIFFRÉ · CONTROL TOWER</b><span id="ctVfsLease" class="ctVfsState">SAS requis</span><span id="ctVfsMirror" class="ctVfsState">miroir privé: 0</span><button id="ctVfsArchive">ARCHIVER FEED</button><button id="ctVfsRefresh">RAFRAÎCHIR</button><button id="ctVfsClear" class="ctVfsDanger">VIDER VFS</button></div><div id="ctVfsList" class="ctVfsList"></div><dialog id="ctVfsDialog"><div id="ctVfsDialogBody"></div><form method="dialog"><button>FERMER</button></form></dialog>`;host.insertAdjacentElement('afterend',n);$('#ctVfsArchive').onclick=()=>archiveCurrent(true);$('#ctVfsRefresh').onclick=render;$('#ctVfsClear').onclick=clearAll}
async function fetchEnvelope(){const mr=await fetch(MANIFEST+'?vfs='+Date.now(),{cache:'no-store',credentials:'omit'});if(!mr.ok)throw new Error('manifest HTTP '+mr.status);const m=await mr.json();if(m.schema!=='GVAULT_CONTROL_TOWER_ENCRYPTED_FEED_V1')throw new Error('manifest schema');const pr=await fetch('./data/'+m.payload.path+'?vfs='+Date.now(),{cache:'no-store',credentials:'omit'});if(!pr.ok)throw new Error('payload HTTP '+pr.status);const cipher=await pr.arrayBuffer();if(cipher.byteLength!==Number(m.payload.size))throw new Error('payload size');if(await sha(cipher)!==m.payload.sha256)throw new Error('payload SHA');return {m,cipher}}
async function archiveCurrent(manual=false){if(!active()){if(manual)alert('Repasse par le SAS principal GVAULT pour ouvrir une fenêtre privée.');return false}try{const {m,cipher}=await fetchEnvelope(),id='CTVFS-'+m.payload.sha256.slice(0,20),exists=await req(tx(SNAP).get(id));if(!exists){const snap={schema:'GVAULT_CONTROL_TOWER_VFS_SNAPSHOT_V1',id,archivedAt:new Date().toISOString(),generatedAt:m.generatedAt||null,manifest:m,cipher:new Blob([cipher],{type:'application/octet-stream'}),payloadSha256:m.payload.sha256,size:cipher.byteLength,source:m.source||{}};await put(SNAP,snap);await put(OPS,{schema:'GVAULT_CONTROL_TOWER_VFS_MIRROR_OP_V1',id:'MOP-'+id,at:snap.archivedAt,action:'UPSERT_ENCRYPTED_SNAPSHOT',snapshotId:id,payloadSha256:snap.payloadSha256,state:'LOCAL_PENDING_PRIVATE_MIRROR'});}await render();return true}catch(e){if(manual)alert('Archive VFS impossible: '+e.message);return false}}
async function inspect(id){if(!active()){alert('SAS principal requis pour déchiffrer cette archive.');return}const snap=await req(tx(SNAP).get(id));if(!snap)return;try{const feed=await session().decryptEnvelope(snap.manifest,snap.cipher),engines=(feed.sources||[]).map(s=>({engine:s.engine,path:s.path,records:(s.records||[]).length})),records=engines.reduce((n,x)=>n+x.records,0);$('#ctVfsDialogBody').innerHTML=`<h3>${id}</h3><p>archivé: ${fmt(snap.archivedAt)}<br>feed: ${fmt(feed.generatedAt)}<br>sources: ${engines.length} · enregistrements: ${records}<br>SHA: ${snap.payloadSha256}</p><pre>${JSON.stringify({source:feed.source,engines,trackRegistry:{tracks:feed.trackRegistry?.tracks?.length||0,workSpecialBindings:feed.trackRegistry?.workSpecialBindings?.length||0}},null,2)}</pre>`;$('#ctVfsDialog').showModal()}catch(e){alert('Déchiffrement VFS refusé: '+e.message)}}
async function removeOne(id){if(!confirm('Supprimer cette archive chiffrée du VFS local ?'))return;await del(SNAP,id);await del(OPS,'MOP-'+id);await put(OPS,{schema:'GVAULT_CONTROL_TOWER_VFS_MIRROR_OP_V1',id:'MDEL-'+Date.now(),at:new Date().toISOString(),action:'DELETE_SNAPSHOT',snapshotId:id,state:'LOCAL_PENDING_PRIVATE_MIRROR'});await render()}
async function clearAll(){if(!confirm('VIDER TOUT LE VFS CHIFFRÉ de cet appareil ? Cette action supprime les snapshots locaux.'))return;await clear(SNAP);await clear(OPS);await put(OPS,{schema:'GVAULT_CONTROL_TOWER_VFS_MIRROR_OP_V1',id:'MDELALL-'+Date.now(),at:new Date().toISOString(),action:'DELETE_ALL_SNAPSHOTS',state:'LOCAL_PENDING_PRIVATE_MIRROR'});await render()}
async function render(){if(!db)return;const snaps=(await all(SNAP)).sort((a,b)=>String(b.archivedAt).localeCompare(String(a.archivedAt))),ops=await all(OPS);$('#ctVfsMirror').textContent='miroir privé: '+ops.filter(x=>x.state==='LOCAL_PENDING_PRIVATE_MIRROR').length+' en attente';$('#ctVfsList').innerHTML=snaps.length?snaps.map(s=>`<article class="ctVfsRow"><div class="ctVfsRowTop"><b>${s.id}</b><span>${fmt(s.archivedAt)}</span></div><div class="ctVfsMeta">${s.size.toLocaleString()} o · ${s.payloadSha256}</div><div class="ctVfsActions"><button data-vfs-open="${s.id}">CONSULTER</button><button data-vfs-del="${s.id}" class="ctVfsDanger">SUPPRIMER</button></div></article>`).join(''):'<div class="empty">Aucune archive chiffrée sur cet appareil.</div>';document.querySelectorAll('[data-vfs-open]').forEach(b=>b.onclick=()=>inspect(b.dataset.vfsOpen));document.querySelectorAll('[data-vfs-del]').forEach(b=>b.onclick=()=>removeOne(b.dataset.vfsDel));updateLease()}
function updateLease(){const s=session()?.getState?.(),n=$('#ctVfsLease');if(!n)return;if(!s?.active){n.textContent='SAS requis';return}const sec=Math.max(0,Math.ceil(s.remainingMs/1000));n.textContent=`fenêtre privée ${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
async function init(){db=await openDb();ui();await render();window.addEventListener('gvault:private-tool-session-active',async()=>{await archiveCurrent(false);await render()});window.addEventListener('gvault:private-tool-session-expired',render);ticker=setInterval(updateLease,1000);window.addEventListener('pagehide',()=>clearInterval(ticker),{once:true});if(active())await archiveCurrent(false)}
init().catch(e=>console.error('[Control Tower encrypted VFS]',e));
