const B=typeof window!=='undefined'&&typeof document!=='undefined',ID='ctLensnouSalon';let pending=null,shown=null,present=false,rev=0,scheduled=false;
const $=s=>B?document.querySelector(s):null,clone=v=>v==null?null:structuredClone(v);
function valid(h){return /^ctarc:[a-f0-9]{64}$/i.test(String(h?.archiveKey||''))}
function essential(h,source){if(!valid(h))return null;return {schema:'GVAULT_LENSNOU_CTARC_ESSENTIAL_V1',source,archiveKey:h.archiveKey,generatedAt:h.generatedAt||null,registryRef:h.registryRef||null,coverage:h.coverage||null,effectiveSourceHeads:h.effectiveSourceHeads||h.sourceHeads||null,qrsprite:h.qrsprite?{status:h.qrsprite.status||null,key:h.qrsprite.key||null,localQrspriteKey:h.localQrspriteKey||null}:{status:h.localQrspriteKey?'LOCAL_SAS':null,key:null,localQrspriteKey:h.localQrspriteKey||null},policy:{visualSalon:true,noRunner:true,noFetch:true,updateOnlyWhenWatchnouAbsent:true}}}
function mount(){if(!B)return null;let n=$('#'+ID);if(n)return n;const host=$('#ctSourceArchiveHealth')||$('#ctSourceUpload')||$('#ctAdaptiveViews')||document.body;n=document.createElement('section');n.id=ID;n.dataset.watchnouPresent='0';n.innerHTML=`<style>#${ID}{margin:0 10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--panel);font:9px ui-monospace,monospace;overflow:hidden}.lnh{display:flex;gap:7px;padding:9px;border-bottom:1px solid var(--line)}.lnh b{color:var(--accent);margin-right:auto}.lnb{display:grid;grid-template-columns:160px 1fr;gap:9px;padding:9px}.lnq{display:grid;grid-template-columns:repeat(16,1fr);aspect-ratio:1;border:1px solid var(--line);background:#fff}.lnq i{display:block}.lnq i.on{background:#111}.lnp{margin:0;white-space:pre-wrap;word-break:break-word;max-height:260px;overflow:auto;border:1px solid var(--line);border-radius:8px;padding:8px}.lnw{border-top:1px solid var(--line);padding:8px 9px;color:var(--muted)}@media(max-width:620px){.lnb{grid-template-columns:1fr}.lnq{width:160px;justify-self:center}}</style><div class="lnh"><b>LENSNOU · SALON</b><span id="lnpresence">WATCHNOU ABSENT</span><span id="lnstate">AUCUN CTARC</span></div><div class="lnb"><div id="lnsprite" class="lnq" aria-label="QRsprite Lensnou"></div><pre id="lnvisible" class="lnp">AUCUN CTARC</pre></div><div id="lnwatch" class="lnw">WATCHNOU · aucune lecture.</div>`;host.insertAdjacentElement('afterend',n);new MutationObserver(()=>setPresent(n.dataset.watchnouPresent==='1')).observe(n,{attributes:true,attributeFilter:['data-watchnou-present']});render();return n}
function sprite(key=''){const box=$('#lnsprite');if(!box)return;let seed=0;for(const c of key)seed=(Math.imul(seed,33)+c.charCodeAt(0))>>>0;box.innerHTML='';for(let i=0;i<256;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const e=document.createElement('i');if(seed&0x80000000)e.className='on';box.append(e)}}
function render(){if(!B)return;mount();const p=$('#lnpresence'),s=$('#lnstate'),v=$('#lnvisible');if(p)p.textContent=present?'WATCHNOU PRÉSENT · SALON FIGÉ':'WATCHNOU ABSENT';if(s)s.textContent=shown?`QRSPRITE #${rev}`:(pending?'MISE À JOUR EN ATTENTE':'AUCUN CTARC');if(v)v.textContent=shown?JSON.stringify(shown,null,2):'AUCUN CTARC';sprite(shown?.archiveKey||'')}
function setPresent(x){const n=!!x;if(n===present)return;present=n;render();if(!present)schedule('WATCHNOU_LEFT_SAFE_MOMENT')}
function schedule(reason){if(scheduled||present||!pending)return;scheduled=true;const run=()=>{scheduled=false;if(present||!pending)return;shown=clone(pending);pending=null;rev++;render();window.dispatchEvent(new CustomEvent('gvault:lensnou-salon-updated',{detail:{schema:'GVAULT_LENSNOU_SALON_UPDATED_V1',reason,revision:rev,archiveKey:shown.archiveKey}}))};if(typeof requestIdleCallback==='function')requestIdleCallback(run,{timeout:1000});else setTimeout(run,0)}
function accept(h,source='ARCHIVE_HEALTH'){const e=essential(h,source);if(!e)return false;pending=e;schedule(source);render();return true}
function bootstrap(){try{const h=window.GVAULT_CONTROL_TOWER_SOURCE_ARCHIVE_HEALTH_V1?.getState?.();if(h)accept(h,'ARCHIVE_HEALTH_VIEW')}catch{}}
function clear(){pending=shown=null;rev=0;render()}
if(B){mount();window.addEventListener('gvault:control-tower-source-archive-health',e=>accept(e.detail,'ARCHIVE_HEALTH_EVENT'));window.addEventListener('gvault:control-tower-source-upload-datasets',e=>{if(e.detail?.archiveHealth)accept(e.detail.archiveHealth,'SOURCE_UPLOAD_DATASETS')});window.addEventListener('gvault:private-tool-session-active',()=>setTimeout(bootstrap,0));window.addEventListener('gvault:private-tool-session-expired',clear);setTimeout(bootstrap,900);window.GVAULT_LENSNOU_V1=Object.freeze({schema:'GVAULT_LENSNOU_V1',accept,bootstrap,getState:()=>({present,revision:rev,shown:clone(shown),pending:clone(pending)})})}
