const B=typeof window!=='undefined'&&typeof document!=='undefined',ID='ctLensnouSalon';let pending=null,shown=null,present=false,rev=0,scheduled=false,blobUrl=null;
const $=s=>B?document.querySelector(s):null,clone=v=>v==null?null:structuredClone(v),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function valid(h){return /^ctarc:[a-f0-9]{64}$/i.test(String(h?.archiveKey||''))}
function essential(h,source){if(!valid(h))return null;return {schema:'GVAULT_LENSNOU_CTARC_ESSENTIAL_V2',source,archiveKey:h.archiveKey,generatedAt:h.generatedAt||null,registryRef:h.registryRef||null,coverage:h.coverage||null,effectiveSourceHeads:h.effectiveSourceHeads||h.sourceHeads||null,qrsprite:h.qrsprite?{status:h.qrsprite.status||null,key:h.qrsprite.key||null,localQrspriteKey:h.localQrspriteKey||null}:{status:h.localQrspriteKey?'LOCAL_SAS':null,key:null,localQrspriteKey:h.localQrspriteKey||null},policy:{visualSalon:true,localBlob:true,noRunner:true,noExternalFetch:true,updateOnlyWhenWatchnouAbsent:true,rawSourceContent:false}}}
function modules(key=''){let seed=0,out='';for(const c of key)seed=(Math.imul(seed,33)+c.charCodeAt(0))>>>0;for(let i=0;i<256;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;out+=`<i class="${seed&0x80000000?'on':''}"></i>`}return out}
function blobHtml(data,revision){const payload=JSON.stringify(data,null,2);return `<!doctype html><html><head><meta charset="utf-8"><meta name="color-scheme" content="dark light"><style>body{margin:0;padding:10px;font:9px ui-monospace,monospace;background:#111;color:#ddd}.head{display:flex;gap:8px;align-items:center;margin-bottom:9px}.head b{margin-right:auto}.grid{display:grid;grid-template-columns:repeat(16,1fr);width:150px;aspect-ratio:1;background:#fff;border:1px solid #555}.grid i{display:block}.grid i.on{background:#111}.wrap{display:grid;grid-template-columns:160px 1fr;gap:10px}pre{margin:0;white-space:pre-wrap;word-break:break-word;border:1px solid #444;border-radius:8px;padding:8px;max-height:260px;overflow:auto}@media(max-width:620px){.wrap{grid-template-columns:1fr}.grid{justify-self:center}}</style></head><body><div class="head"><b>LENSNOU · BLOB SALON</b><span>QRSPRITE #${revision}</span></div><div class="wrap"><div class="grid" aria-label="QRsprite Lensnou">${modules(data.archiveKey)}</div><pre id="lensnouBlobPayload">${esc(payload)}</pre></div></body></html>`}
function mount(){if(!B)return null;let n=$('#'+ID);if(n)return n;const host=$('#ctSourceArchiveHealth')||$('#ctSourceUpload')||$('#ctAdaptiveViews')||document.body;n=document.createElement('section');n.id=ID;n.dataset.watchnouPresent='0';n.innerHTML=`<style>#${ID}{margin:0 10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--panel);font:9px ui-monospace,monospace;overflow:hidden}.lnh{display:flex;gap:7px;padding:9px;border-bottom:1px solid var(--line)}.lnh b{color:var(--accent);margin-right:auto}.lnframe{display:block;width:calc(100% - 18px);height:330px;margin:9px;border:1px solid var(--line);border-radius:8px;background:var(--panel2)}.lnw{border-top:1px solid var(--line);padding:8px 9px;color:var(--muted)}</style><div class="lnh"><b>LENSNOU · SALON BLOB</b><span id="lnpresence">WATCHNOU ABSENT</span><span id="lnstate">AUCUN CTARC</span></div><iframe id="lnblobframe" class="lnframe" title="Blob visuel Lensnou"></iframe><div id="lnwatch" class="lnw">WATCHNOU · aucune lecture.</div>`;host.insertAdjacentElement('afterend',n);new MutationObserver(()=>setPresent(n.dataset.watchnouPresent==='1')).observe(n,{attributes:true,attributeFilter:['data-watchnou-present']});render();return n}
function render(){if(!B)return;mount();const p=$('#lnpresence'),s=$('#lnstate');if(p)p.textContent=present?'WATCHNOU PRÉSENT · BLOB FIGÉ':'WATCHNOU ABSENT';if(s)s.textContent=shown?`BLOB QRSPRITE #${rev}`:(pending?'MISE À JOUR EN ATTENTE':'AUCUN CTARC')}
function setPresent(x){const n=!!x;if(n===present)return;present=n;render();if(!present)schedule('WATCHNOU_LEFT_SAFE_MOMENT')}
function materialize(data,revision){return new Promise(resolve=>{const frame=$('#lnblobframe');if(!frame)return resolve(false);const blob=new Blob([blobHtml(data,revision)],{type:'text/html'}),next=URL.createObjectURL(blob),old=blobUrl;blobUrl=next;let done=false;const finish=()=>{if(done)return;done=true;if(old)URL.revokeObjectURL(old);resolve(true)};frame.onload=finish;frame.src=next;setTimeout(finish,1200)})}
function schedule(reason){if(scheduled||present||!pending)return;scheduled=true;const run=async()=>{scheduled=false;if(present||!pending)return;shown=clone(pending);pending=null;rev++;render();await materialize(shown,rev);window.dispatchEvent(new CustomEvent('gvault:lensnou-salon-updated',{detail:{schema:'GVAULT_LENSNOU_SALON_UPDATED_V2',reason,revision:rev,archiveKey:shown.archiveKey,transport:'LOCAL_BLOB_VISUAL'}}))};if(typeof requestIdleCallback==='function')requestIdleCallback(()=>void run(),{timeout:1000});else setTimeout(()=>void run(),0)}
function accept(h,source='ARCHIVE_HEALTH'){const e=essential(h,source);if(!e)return false;pending=e;schedule(source);render();return true}
function bootstrap(){try{const h=window.GVAULT_CONTROL_TOWER_SOURCE_ARCHIVE_HEALTH_V1?.getState?.();if(h)accept(h,'ARCHIVE_HEALTH_VIEW')}catch{}}
function clear(){pending=shown=null;rev=0;scheduled=false;if(blobUrl){URL.revokeObjectURL(blobUrl);blobUrl=null}const f=$('#lnblobframe');if(f)f.removeAttribute('src');render()}
if(B){mount();window.addEventListener('gvault:control-tower-source-archive-health',e=>accept(e.detail,'ARCHIVE_HEALTH_EVENT'));window.addEventListener('gvault:control-tower-source-upload-datasets',e=>{if(e.detail?.archiveHealth)accept(e.detail.archiveHealth,'SOURCE_UPLOAD_DATASETS')});window.addEventListener('gvault:private-tool-session-active',()=>setTimeout(bootstrap,0));window.addEventListener('gvault:private-tool-session-expired',clear);window.addEventListener('pagehide',()=>{if(blobUrl)URL.revokeObjectURL(blobUrl)},{once:true});setTimeout(bootstrap,900);window.GVAULT_LENSNOU_V1=Object.freeze({schema:'GVAULT_LENSNOU_V2_LOCAL_BLOB',accept,bootstrap,getState:()=>({present,revision:rev,blobReady:!!blobUrl,archiveKey:shown?.archiveKey||null,pendingArchiveKey:pending?.archiveKey||null})})}
