import assert from 'node:assert/strict';
import {TTL_SECONDS,capsuleFromRow,uploadCapsule} from './public-vfs-weekly-v1.mjs';
const cipher='b'.repeat(64),drop='c'.repeat(64),row={schema:'GVAULT_CONTROL_TOWER_SOURCE_UPLOAD_VFS_ROW_V1',qrspriteKey:`ctqru:${drop}:${cipher}`,archiveKey:`ctarc:${'d'.repeat(64)}`,cipherSha256:cipher,storedAt:'2026-08-29T00:00:00.000Z',fileCount:4,cipherBytes:3,manifest:{schema:'GVAULT_CONTROL_TOWER_LOCAL_QRSPRITE_ENVELOPE_V1',payload:{sha256:cipher,size:3},crypto:{cipher:'AES-256-GCM'}},sprite:{schema:'GVAULT_QRSPRITE_SOURCE_UPLOAD_ATLAS_V1',cipherSha256:cipher,cipherBytes:3,tiles:[{index:0,byteOffset:0,byteLength:3,dataB64:'AQID'}]}};
const start=new Date('2026-08-29T00:17:00.000Z');
const cycleKey='ctw:2026-08-29T00:17:00.000Z';
const c=capsuleFromRow(row,{id:'a'.repeat(32),now:start,cycleKey,cycleStartedAt:start.toISOString(),cycleNextAt:'2026-09-05T00:17:00.000Z'});
assert.equal(c.schema,'GVAULT_CONTROL_TOWER_PUBLIC_VFS_CAPSULE_V1');
assert.equal(c.id,'a'.repeat(32));
assert.equal(c.cycle.key,cycleKey);
assert.equal(c.cycle.startedAt,'2026-08-29T00:17:00.000Z');
assert.equal(c.cycle.nextAt,'2026-09-05T00:17:00.000Z');
assert.equal(c.cycle.contract,'essai/control-tower/weekly-shared-checkpoint-contract-v1.json');
assert.equal(c.packet.qrspriteKey,row.qrspriteKey);
assert.equal(c.packet.manifest.payload.sha256,cipher);
assert.equal(c.policy.plaintextAllowed,false);
assert.equal(c.policy.gitHistoryPersistence,false);
assert.equal(c.policy.encryptionAuthority,'INHERITED_SAS_SESSION');
assert.equal(TTL_SECONDS,604800);
assert.equal(new Date(c.expiresAt)-new Date(c.createdAt),604800000);
let called=0;const ok=await uploadCapsule(c,{url:'https://gateway.test/v1/public-vfs',fetchFn:async(_u,o)=>{called++;assert.equal(o.method,'POST');const b=JSON.parse(o.body);assert.equal(b.id,c.id);assert.equal(b.cycle.key,cycleKey);return new Response(JSON.stringify({ok:true,id:c.id,ttlSeconds:604800,cycleKey}),{status:201,headers:{'content-type':'application/json'}})}});
assert.equal(called,1);assert.equal(ok.status,'UPLOADED');assert.equal(ok.receipt.ttlSeconds,604800);assert.equal(ok.receipt.cycleKey,cycleKey);
const noEndpoint=await uploadCapsule(c,{url:'',fetchFn:async()=>{throw new Error('should not call')}});assert.equal(noEndpoint.status,'PENDING_ENDPOINT');
const net=await uploadCapsule(c,{url:'https://gateway.test/v1/public-vfs',fetchFn:async()=>{throw new Error('offline')}});assert.equal(net.status,'PENDING_NETWORK');
assert.throws(()=>capsuleFromRow({...row,qrspriteKey:'ctqr:bad'}),/CTQRU_REQUIRED/);
console.log('CONTROL_TOWER_PUBLIC_VFS_WEEKLY_TEST PASS 21 assertions');
