const REPOS={pages:'mourchoua-commits/Gvault-Pages',stable:'mourchoua-commits/GvaultStable'};
const POLL_MS=600000,LEADER_MS=90000,LEADER_KEY='gvault.controlTower.publicLive.leader.v1';
const id=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
let timer=null,leaderTimer=null,events=[],lastRefresh=null,lastError='',rateRemaining=null,stopped=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
function leader(){return read(LEADER_KEY)}function isLeader(){const x=leader();return x?.id===id&&Number(x.expiresAt)>Date.now()}function acquire(){const x=leader();if(!x||Number(x.expiresAt)<=Date.now()||x.id===id){write(LEADER_KEY,{id,expiresAt:Date.now()+LEADER_MS});return true}return false}function renew(){if(stopped)return;if(acquire())write(LEADER_KEY,{id,expiresAt:Date.now()+LEADER_MS});renderState()}
function release(){if(leader()?.id===id)try{localStorage.removeItem(LEADER_KEY)}catch{}}
async function api(url){const r=await fetch(url,{cache:'no-store',credentials:'omit',headers:{Accept:'application/vnd.github+json'}});const rem=Number(r.headers.get('x-ratelimit-remaining'));if(Number.isFinite(rem))rateRemaining=rem;if(!r.ok)throw new Error(`HTTP_${r.status}`);return r.json()}
function commitEvent(row,engine,project){return {id:`${engine}:${row.sha}`,engine,type:'git_commit',status:'observed',severity:'info',at:row.commit?.committer?.date||row.commit?.author?.date||'',summary:String(row.commit?.message||'').split(/\r?\n/)[0]||'commit',sha:row.sha,project,proof:row.html_url||'',authority:'PUBLIC_DIRECT'}}
function runEvent(r){const conclusion=r.conclusion||r.status||'unknown',sev=conclusion==='failure'?'warning':conclusion==='cancelled'?'warning':conclusion==='success'?'ok':'info';return {id:`pages-run:${r.id}`,engine:'pages-actions',type:'workflow_run',status:conclusion,severity:sev,at:r.updated_at||r.created_at||'',summary:`${r.name||'workflow'} · ${conclusion}`,sha:r.head_sha||'',project:'Gvault-Pages',proof:r.html_url||'',authority:'PUBLIC_DIRECT'}}
async function refresh(force=false){if(!force&&!acquire()){renderState();return}try{const [pc,runs,sc]=await Promise.all([api(`https://api.github.com/repos/${REPOS.pages}/commits?sha=main&per_page=24`),api(`https://api.github.com/repos/${REPOS.pages}/actions/runs?branch=main&per_page=18`),api(`https://api.github.com/repos/${REPOS.stable}/commits?sha=main&per_page=12`)]);const rows=[];(Array.isArray(pc)?pc:[]).forEach(x=>rows.push(commitEvent(x,'pages-git','Gvault-Pages')));(runs?.workflow_runs||[]).forEach(x=>rows.push(runEvent(x)));(Array.isArray(sc)?sc:[]).forEach(x=>rows.push(commitEvent(x,'stable-git','GvaultStable')));const map=new Map();for(const e of rows)map.set(e.id,e);events=[...map.values()].sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0));lastRefresh=new Date();lastError='';render();window.dispatchEvent(new CustomEvent('gvault:control-tower-public-live',{detail:{count:events.length,lastRefresh:lastRefresh.toISOString(),rateRemaining,events:structuredClone(events)}}))}catch(e){lastError=String(e?.message||e);renderState()}}
function ensureUi(){if($('#ctPublicLive'))return;const anchor=$('#ctSourceRouter')||document.querySelector('.kpis')||document.querySelector('main')||document.body;const n=document.createElement('section');n.id='ctPublicLive';n.innerHTML=`<style>#ctPublicLive{margin:0 10px 10px;border:1px solid var(--line);border-radius:10px;background:var(--panel);overflow:hidden;font:9px ui-monospace,monospace}.ctplHead{padding:8px;border-bottom:1px solid var(--line);display:flex;gap:8px;align-items:center;flex-wrap:wrap}.ctplHead b{color:var(--accent);margin-right:auto}.ctplState{color:var(--muted)}.ctplHead button{font-size:8px;padding:6px 8px}.ctplList{display:grid;gap:5px;padding:8px;max-height:300px;overflow:auto}.ctplRow{width:100%;text-align:left;border:1px solid var(--line);border-radius:8px;padding:7px;background:var(--panel2);color:var(--text)}.ctplRow.warn{border-left:3px solid var(--warn)}.ctplRow.ok{border-left:3px solid var(--ok)}.ctplTop{display:flex;gap:6px;justify-content:space-between;color:var(--muted);font-size:8px}.ctplSummary{margin-top:4px;font-size:9px;white-space:normal}.ctplMeta{margin-top:4px;color:var(--muted);font-size:7px;word-break:break-all}#ctPublicDialog{max-width:min(92vw,760px);background:var(--panel);color:var(--text);border:1px solid var(--line);border-radius:10px}#ctPublicDialog pre{max-height:55vh;overflow:auto;white-space:pre-wrap;word-break:break-word;font-size:8px}</style><div class="ctplHead"><b>PUBLIC DIRECT · OBSERVABILITÉ RÉELLE</b><span id="ctplState" class="ctplState">chargement…</span><button id="ctplRefresh">RAFRAÎCHIR</button></div><div id="ctplList" class="ctplList"></div><dialog id="ctPublicDialog"><div id="ctPublicDialogBody"></div><form method="dialog"><button>FERMER</button></form></dialog>`;anchor.insertAdjacentElement('afterend',n);$('#ctplRefresh').onclick=()=>refresh(true)}
function renderState(){ensureUi();const n=$('#ctplState');if(!n)return;if(lastError)n.textContent=`DEGRADED · ${lastError}${rateRemaining!=null?` · quota ${rateRemaining}`:''}`;else if(lastRefresh)n.textContent=`${events.length} événements · ${lastRefresh.toLocaleTimeString()}${rateRemaining!=null?` · quota ${rateRemaining}`:''}`;else n.textContent=isLeader()?'chargement…':'veille passive'}
function open(id){const e=events.find(x=>x.id===id);if(!e)return;$('#ctPublicDialogBody').innerHTML=`<h3>${esc(e.engine)}</h3><p>${esc(e.summary)}</p><pre>${esc(JSON.stringify(e,null,2))}</pre>${e.proof?`<p><a href="${esc(e.proof)}" target="_blank" rel="noopener">preuve publique GitHub</a></p>`:''}`;$('#ctPublicDialog').showModal()}
function render(){ensureUi();renderState();const list=$('#ctplList');if(!list)return;list.innerHTML=events.length?events.slice(0,54).map(e=>`<button class="ctplRow ${e.severity==='warning'?'warn':e.severity==='ok'?'ok':''}" data-ctpl="${esc(e.id)}"><div class="ctplTop"><b>${esc(e.engine)}</b><time>${esc(new Date(e.at).toLocaleString())}</time></div><div class="ctplSummary">${esc(e.summary)}</div><div class="ctplMeta">${esc(e.type)} · ${esc(e.status)}${e.sha?` · ${esc(e.sha.slice(0,12))}`:''}</div></button>`).join(''):'<div class="empty">Aucune observation publique chargée.</div>';document.querySelectorAll('[data-ctpl]').forEach(b=>b.onclick=()=>open(b.dataset.ctpl))}
function schedule(){clearTimeout(timer);if(!stopped)timer=setTimeout(async()=>{renew();if(isLeader())await refresh(true);schedule()},POLL_MS)}
function wake(){if(document.visibilityState==='visible'){renew();if(!lastRefresh||Date.now()-lastRefresh.getTime()>POLL_MS)void refresh(true)}}
function stop(){stopped=true;clearTimeout(timer);clearInterval(leaderTimer);release();document.removeEventListener('visibilitychange',wake);window.removeEventListener('focus',wake)}
ensureUi();renew();leaderTimer=setInterval(renew,Math.floor(LEADER_MS/2));document.addEventListener('visibilitychange',wake);window.addEventListener('focus',wake);window.addEventListener('pagehide',stop,{once:true});setTimeout(()=>{void refresh(true);schedule()},700);
window.GVAULT_CONTROL_TOWER_PUBLIC_LIVE_V1=Object.freeze({schema:'GVAULT_CONTROL_TOWER_PUBLIC_LIVE_V1',refresh:()=>refresh(true),getEvents:()=>structuredClone(events),getState:()=>({events:events.length,lastRefresh:lastRefresh?.toISOString()||null,lastError,rateRemaining,leader:isLeader()})});