const MANIFEST='../control-tower/data/manifest.json';
const OUTBOX_KEY='gvault.gadmin.actionOutbox.v1';
let password='',feed=null,queue=[],official=[],policy=null,alerts=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b64bytes=s=>{const bin=atob(String(s||''));return Uint8Array.from(bin,c=>c.charCodeAt(0))};
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async b=>hex(await crypto.subtle.digest('SHA-256',b));
function log(text,kind=''){const n=document.createElement('div');n.textContent=`${new Date().toLocaleTimeString()}  ${text}`;if(kind)n.style.color=kind==='bad'?'var(--bad)':kind==='ok'?'var(--ok)':'var(--warn)';$('#log').appendChild(n);$('#log').scrollTop=$('#log').scrollHeight}
function setState(text,kind=''){const n=$('#state');n.textContent=text;n.className='pill'+(kind==='ok'?' ok':'');if(kind==='bad')n.style.color='var(--bad)';else if(kind==='warn')n.style.color='var(--warn)';else n.style.color=''}
function showNotice(text){const n=$('#notice');n.hidden=false;n.textContent=text}
function hideNotice(){$('#notice').hidden=true}
function outbox(){try{const x=JSON.parse(localStorage.getItem(OUTBOX_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function saveOutbox(x){localStorage.setItem(OUTBOX_KEY,JSON.stringify(x.slice(-500)))}
function queueIntent(action,entry){const rows=outbox();const item={schema:'GVAULT_GADMIN_ACTION_OUTBOX_V1',id:`GAO-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,at:new Date().toISOString(),action,receiptId:entry?.receiptId||null,projectName:entry?.projectName||null,state:'LOCAL_PENDING_SERVER_BRIDGE',payload:entry||null};rows.push(item);saveOutbox(rows);renderKpis();log(`${action} préparé · ${item.receiptId||item.projectName||item.id} · LOCAL_PENDING_SERVER_BRIDGE`,'warn')}
async function probe(){try{const r=await fetch(MANIFEST+'?probe='+Date.now(),{cache:'no-store',credentials:'omit'});if(!r.ok)throw new Error('HTTP '+r.status);const m=await r.json();if(m.schema!=='GVAULT_CONTROL_TOWER_ENCRYPTED_FEED_V1')throw new Error('schema');$('#open').disabled=false;hideNotice();return true}catch{$('#open').disabled=true;showNotice('FEED CHIFFRÉ EN ATTENTE · la capacité GitHub Actions privée est actuellement épuisée. Ce statut ne signifie pas que ton mot de passe est faux. Aucun PAT GitHub navigateur n’est requis.');setState('FEED EN ATTENTE','warn');return false}}
async function decrypt(secret){const mr=await fetch(MANIFEST+'?ts='+Date.now(),{cache:'no-store',credentials:'omit'});if(!mr.ok)throw new Error('feed manifest HTTP '+mr.status);const m=await mr.json();if(m.schema!=='GVAULT_CONTROL_TOWER_ENCRYPTED_FEED_V1')throw new Error('manifest schema');const pr=await fetch('../control-tower/data/'+m.payload.path+'?ts='+Date.now(),{cache:'no-store',credentials:'omit'});if(!pr.ok)throw new Error('feed payload HTTP '+pr.status);const cipher=await pr.arrayBuffer();if(cipher.byteLength!==Number(m.payload.size))throw new Error('payload size mismatch');if(await sha(cipher)!==m.payload.sha256)throw new Error('payload SHA mismatch');const raw=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64bytes(m.crypto.saltB64),iterations:Number(m.crypto.iterations),hash:'SHA-256'},raw,{name:'AES-GCM',length:256},false,['decrypt']);let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64bytes(m.crypto.ivB64)},key,cipher)}catch{throw new Error('mot de passe SAS incorrect ou feed invalide')}if(plain.byteLength!==Number(m.source.size)||await sha(plain)!==m.source.sha256)throw new Error('plain integrity mismatch');const f=JSON.parse(new TextDecoder().decode(plain));if(f.schema!=='GVAULT_CONTROL_TOWER_FEED_V1')throw new Error('feed schema');return f}
function source(engine){return (feed?.sources||[]).find(s=>s.engine===engine)||null}
function sources(engine){return (feed?.sources||[]).filter(s=>s.engine===engine)}
function severityOf(x){const s=String(x?.severity||x?.level||x?.status||'').toLowerCase();if(/critical|fatal|error|fail|blocked/.test(s))return'critical';if(/warn|degrad|pending|orphan|unresolved/.test(s))return'warning';return'ok'}
function summaryOf(x){return String(x?.summary||x?.message||x?.title||x?.type||x?.schema||'événement').slice(0,240)}
function atOf(x){return x?.timestamp||x?.created_at||x?.createdAt||x?.updatedAt||x?.observedAt||''}
function hydrate(){policy=source('gadmin-policy')?.records?.[0]||null;const intake=source('gadmin-intake')?.records?.[0]||null;queue=Array.isArray(intake?.entries)?intake.entries:[];const reg=source('gadmin-official')?.records?.[0]||null;official=Array.isArray(reg?.projects)?reg.projects:[];alerts=[];for(const s of feed?.sources||[]){if(!['vigie','vigie-report','continuity','actions-capacity','ci-budget','project-review','changelog-decision','private-intake'].includes(s.engine))continue;for(const raw of s.records||[]){const severity=severityOf(raw);if(severity!=='ok'||s.engine==='vigie')alerts.push({engine:s.engine,severity,summary:summaryOf(raw),at:atOf(raw),raw})}}alerts.sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0));render()}
function renderKpis(){$('#kQueue').textContent=queue.filter(x=>String(x.validationStatus||'').toUpperCase()!=='VALIDATED'&&String(x.publicStatus||'').toUpperCase()!=='PUBLISHED').length;$('#kOfficial').textContent=official.length;$('#kAlerts').textContent=alerts.filter(x=>x.severity!=='ok').length;$('#kOutbox').textContent=outbox().length}
function renderPolicy(){const mode=policy?.publicationMode||'—';$('#policyMode').textContent=mode;$('#policy').innerHTML=`<dt>MODE</dt><dd>${esc(mode)}</dd><dt>SCHÉMA</dt><dd>${esc(policy?.schema||'—')}</dd><dt>MAJ</dt><dd>${esc(policy?.updatedAt||'—')}</dd><dt>RÈGLE</dt><dd>${esc(policy?.description||'—')}</dd>`}
function renderQueue(){const box=$('#queue');if(!queue.length){box.innerHTML='<div class="empty">Aucune entrée dans la file Admin.</div>';return}box.innerHTML=queue.slice(0,200).map(e=>`<article class="item"><div class="itemTop"><b>${esc(e.receiptId||'sans receipt')}</b><span>${esc(e.receivedAt||e.importedAt||'')}</span></div><h3>${esc(e.projectName||e.fileName||'Projet')}</h3><p>${esc(e.fileName||'')} · ${Number(e.sizeBytes||0).toLocaleString()} o</p><p>validation=${esc(e.validationStatus||'—')} · public=${esc(e.publicStatus||'—')} · mode=${esc(e.publicationMode||'—')}</p><div class="actions"><button data-intent="VALIDATE_REQUEST" data-receipt="${esc(e.receiptId||'')}">PRÉPARER VALIDATION</button><button data-intent="HOLD_REQUEST" data-receipt="${esc(e.receiptId||'')}">PRÉPARER ATTENTE</button></div></article>`).join('');document.querySelectorAll('[data-intent]').forEach(b=>b.onclick=()=>{const e=queue.find(x=>String(x.receiptId||'')===b.dataset.receipt);if(e)queueIntent(b.dataset.intent,e)})}
function renderAlerts(){const box=$('#alerts');if(!alerts.length){box.innerHTML='<div class="empty">Aucune alerte/activité disponible.</div>';return}box.innerHTML=alerts.slice(0,160).map(a=>`<article class="item alert ${a.severity}"><div class="itemTop"><b>${esc(a.engine)}</b><span>${esc(a.at||'')}</span></div><h3>${esc(a.summary)}</h3><p>${esc(String(a.raw?.status||a.raw?.schema||''))}</p></article>`).join('')}
function render(){renderKpis();renderPolicy();renderQueue();renderAlerts();$('#sourceAge').textContent=feed?.generatedAt?new Date(feed.generatedAt).toLocaleString():'—'}
async function open(){password=$('#password').value;$('#password').value='';if(!password)return;setState('DÉCHIFFREMENT…','warn');try{feed=await decrypt(password);hydrate();setState('ADMIN LIVE','ok');log(`SAS GAdmin PASS · même mot de passe GVAULT · main=${String(feed.source?.mainCommit||'').slice(0,12)} · intake=${String(feed.source?.intakeCommit||'').slice(0,12)}`,'ok')}catch(e){password='';feed=null;setState('AUTH FAIL','bad');log('SAS FAIL · '+e.message,'bad')}}
function lock(){password='';feed=null;queue=[];official=[];policy=null;alerts=[];setState('VERROUILLÉ');$('#policyMode').textContent='—';$('#policy').innerHTML='';$('#queue').innerHTML='<div class="empty">GAdmin verrouillé.</div>';$('#alerts').innerHTML='<div class="empty">GAdmin verrouillé.</div>';renderKpis();log('GAdmin fermé · mot de passe effacé de la mémoire de la page','warn')}
function command(line){const [cmd,...rest]=line.trim().split(/\s+/);if(!cmd)return;log('> '+line);switch(cmd.toLowerCase()){case'help':log('help · status · queue · alerts · policy · outbox · clear');break;case'status':log(`${$('#state').textContent} · queue=${queue.length} · official=${official.length} · alerts=${alerts.length} · outbox=${outbox().length}`);break;case'queue':log(queue.map(x=>`${x.receiptId||'—'}:${x.projectName||x.fileName||'—'}:${x.validationStatus||'—'}`).join(' · ')||'queue vide');break;case'alerts':log(alerts.slice(0,12).map(x=>`${x.severity}:${x.engine}:${x.summary}`).join(' · ')||'aucune alerte');break;case'policy':log(policy?JSON.stringify(policy):'policy indisponible');break;case'outbox':log(JSON.stringify(outbox().slice(-20)));break;case'clear':$('#log').innerHTML='';break;default:log('commande inconnue · help','warn')}}

document.addEventListener('DOMContentLoaded',async()=>{$('#open').onclick=open;$('#lock').onclick=lock;$('#terminal').onsubmit=e=>{e.preventDefault();const i=$('#cmd');command(i.value);i.value=''};render();await probe();log('GADMIN prêt · accès privé par feed chiffré · aucun token GitHub navigateur')});
window.addEventListener('pagehide',()=>{password='';feed=null},{once:true});
